spring.application.name=copro

# Postgres local
spring.datasource.url=jdbc:postgresql://localhost:5432/copro_db
spring.datasource.username=postgres
spring.datasource.password=

# JPA (simple)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
